name: 'Documentation'
description: 'Build the documentation'
inputs:
  folders:
    description: 'Folders with documentation to build'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.folders }}
